voice_group littleroot_compact
	voice_keysplit_all voicegroup_rs_drumset
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 188
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano
	voice_square_2_alt 60, 0, 2, 0, 1, 5, 2
	voice_keysplit voicegroup_strings_keysplit, keysplit_strings
	voice_keysplit voicegroup_strings_keysplit, keysplit_strings
	voice_keysplit voicegroup_trumpet_keysplit, keysplit_trumpet