OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "When a POKéMON battle starts, the one\n"
	.string "at the left of the list goes out first.\p"
	.string "So, when you get more POKéMON in your\n"
	.string "party, try switching around the order\l"
	.string "of your POKéMON.\p"
	.string "It could give you an advantage.$"

PhenacCity_House1_Woman1::
	msgbox PhenacCity_House1_Woman1_Dialogue, MSGBOX_NPC
	end

PhenacCity_House1_Woman1_Dialogue:
	.string "That Team Snagem doesn't frighten me.\n"
	.string "After all, where those people are is far\l"
	.string "away from here.\l"
	.string "They wouldn't come out here.\p"
	.string "The thugs of Pyrite Town...\n"
	.string "They're much more frightening to me.$"

PhenacCity_House1_Man1::
	msgbox PhenacCity_House1_Man1_Dialogue, MSGBOX_NPC
	end

PhenacCity_House1_Man1_Dialogue:
	.string "There's been nothing but news about\n"
	.string "Team Snagem on every channel all\l"
	.string "day long.\p"
	.string "Usually, they'd have at least one\n"
	.string "channel showing anime or something.\p"
	.string "Grumble...$"
