Phenac_Mayor_House_Upstiars_Lady::
# 2 "data/maps/Phenac_Mayor_House_Upstaris/scripts.pory"
	lock
# 3 "data/maps/Phenac_Mayor_House_Upstaris/scripts.pory"
	faceplayer
# 4 "data/maps/Phenac_Mayor_House_Upstaris/scripts.pory"
	msgbox Phenac_Mayor_House_Upstiars_Lady_Text_0, MSGBOX_DEFAULT
# 7 "data/maps/Phenac_Mayor_House_Upstaris/scripts.pory"
	release
	end


Phenac_Mayor_House_Upstaris_MapScripts::
	.byte 0


Phenac_Mayor_House_Upstiars_Lady_Text_0:
# 4 "data/maps/Phenac_Mayor_House_Upstaris/scripts.pory"
	.string "Oh, hi. Aren't you a cute guy?\p"
	.string "Giggle...\n"
	.string "It must be nice to travel with a cute\l"
	.string "girlfriend.$"
